# base_dir: "/var/www/oslc.co/public/ns/"
base_dir: "/Users/andrew/git/oslc/web/website/content/ns"
# compression: true
# cors_allowed: true
ns_definitions:
  - prefix: "/ns/core"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/core-vocab.html"
    files:
      rdfxml: "core/core-vocab.rdf"
      ntriples: "core/core-vocab.nt"
      jsonld: "core/core-vocab.jsonld"
      turtle: "core/core-vocab.ttl"
  - prefix: "/ns/core/shapes/3.0"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/core-shapes.html"
    files:
      rdfxml: "core/core-shapes.rdf"
      ntriples: "core/core-shapes.nt"
      jsonld: "core/core-shapes.jsonld"
      turtle: "core/core-shapes.ttl"
  - prefix: "/ns/config"
    core_version: "2.0" # these are old files
    html_uri: "https://oslc-op.github.io/oslc-specs/specs/config/config-vocab.html"
    files:
      rdfxml: "config/config-vocab.rdf"
      ntriples: "config/config-vocab.nt"
      jsonld: "config/config-vocab.jsonld"
      turtle: "config/config-vocab.ttl"
  - prefix: "/ns/cm"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/bin/view/Main/CmVocabulary.html"
    files:
      rdfxml: "cm/cm.rdf"
      ntriples: "cm/cm.nt"
      jsonld: "cm/cm.jsonld"
      turtle: "cm/cm.ttl"
  - prefix: "/ns/rm"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/bin/view/Main/RmVocabulary.html"
    files:
      rdfxml: "rm/requirements-management-vocab.rdf"
      ntriples: "rm/requirements-management-vocab.nt"
      jsonld: "rm/requirements-management-vocab.jsonld"
      turtle: "rm/requirements-management-vocab.ttl"
  - prefix: "/ns/qm"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/bin/view/Main/QmVocabulary.html"
    files:
      rdfxml: "qm/qm.rdf"
      ntriples: "qm/qm.nt"
      jsonld: "qm/qm.jsonld"
      turtle: "qm/qm.ttl"
  - prefix: "/ns/am"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/wiki/architecture-management/OSLC-Architecture-Management-Vocabulary/index.html"
    files:
      rdfxml: "am/am.rdf"
      ntriples: "am/am.nt"
      jsonld: "am/am.jsonld"
      turtle: "am/am.ttl"
  - prefix: "/ns/asset"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/wiki/asset-management/OSLC-Asset-Management-Vocabulary/index.html"
    files:
      rdfxml: "asset/asset.rdf"
      ntriples: "asset/asset.nt"
      jsonld: "asset/asset.jsonld"
      turtle: "asset/asset.ttl"
  - prefix: "/ns/auto"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/wiki/automation/OSLC-Automation-Vocabulary/index.html"
    files:
      rdfxml: "auto/automation-vocab.rdf"
      ntriples: "auto/automation-vocab.nt"
      jsonld: "auto/automation-vocab.jsonld"
      turtle: "auto/automation-vocab.ttl"
  - prefix: "/ns/perfmon"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/wiki/performance-monitoring/OSLC-Performance-Monitoring-Vocabulary/index.html"
    files:
      rdfxml: "perfmon/performance-monitoring-vocab.rdf"
      ntriples: "perfmon/performance-monitoring-vocab.nt"
      jsonld: "perfmon/performance-monitoring-vocab.jsonld"
      turtle: "perfmon/performance-monitoring-vocab.ttl"
  - prefix: "/ns/ems"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/wiki/estimation-and-measurement/EMS-1.0-REST-API-Data-Model/index.html"
    files:
      rdfxml: "ems/ems.rdf"
      ntriples: "ems/ems.nt"
      jsonld: "ems/ems.jsonld"
      turtle: "ems/ems.ttl"